services:
  db:
    image: postgres:16-alpine
    container_name: prototype-pipeline-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: prototype_pipeline
    ports:
      - "5434:5432"
    volumes:
      - pipeline_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline -d prototype_pipeline"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pipeline_pgdata:
