from datetime import date, timedelta

from sqlalchemy.orm import Session

from app.models.entities import (
    ActivityLog,
    Document,
    Initiative,
    Notification,
    RiskValueStream,
    SolutionTeam,
    User,
    WorkflowStage,
)
from app.models.lifecycle import IpsafeActivity


STAGES = [
    ("Idea Submitted", "idea_submitted", 1),
    ("Management Review", "management_review", 2),
    ("Requirements & User Stories", "requirements", 3),
    ("Solution Review", "solution_review", 4),
    ("Design", "design", 5),
    ("Ready to Build", "ready_to_build", 6),
    ("Build in Progress", "build_in_progress", 7),
    ("Show & Tell", "show_and_tell", 8),
    ("Feedback / Refinement", "feedback", 9),
    ("Prototype Ready", "prototype_ready", 10),
    ("IPSAFE Capability Demonstrator", "ipsafe_cd", 11),
    ("Capability Demonstrator Approved", "cd_approved", 12),
    ("Solution Candidate", "solution_candidate", 13),
    ("Deployable Solution", "deployable_solution", 14),
    ("Completed / Demonstrated", "completed", 15),
]

VALUE_STREAMS = [
    ("Credit Risk", "CR", "Credit risk analytics and early warning"),
    ("Market Risk", "MR", "Market risk measurement and stress testing"),
    ("Counterparty Credit Risk", "CCR", "CCR exposure and XVA"),
    ("Liquidity Risk", "LR", "Liquidity risk monitoring"),
    ("Climate Risk", "CLR", "Climate scenario and transition risk"),
    ("Compliance", "CMP", "Regulatory compliance enablement"),
    ("Financial Crime", "FC", "AML, fraud and financial crime"),
    ("Insurance Risk", "IR", "Insurance risk and actuarial"),
    ("Audit", "AUD", "Internal audit analytics"),
    ("AI Risk", "AIR", "AI model risk and governance"),
    ("Cyber Risk", "CYB", "Cyber risk detection and response"),
]

SOLUTION_TEAMS = [
    ("Solution Team 1", 8),
    ("Solution Team 2", 10),
    ("Solution Team 3", 7),
    ("Solution Team 4", 9),
]

IPSAFE_ACTIVITIES = [
    ("governance_charter", "Governance charter approved", "CD scope and ownership confirmed", 1, True, True),
    ("risk_assessment", "Risk assessment completed", "Key risks and controls identified", 2, True, True),
    ("data_classification", "Data classification", "Data sensitivity and handling defined", 3, True, True),
    ("architecture_review", "Architecture review", "Target architecture reviewed", 4, True, True),
    ("security_controls", "Security controls mapped", "Control mapping for demonstrator", 5, True, True),
    ("model_validation", "Model/methodology validation", "Validation evidence captured", 6, True, True),
    ("ops_runbook", "Operations runbook", "Support and ops model drafted", 7, False, True),
    ("prod_readiness", "Production readiness checklist", "Deployability criteria met", 8, False, True),
    ("resilience_testing", "Resilience & DR testing", "Failover and recovery proven", 9, False, True),
    ("client_deploy_pack", "Client deploy pack", "Reuse/deploy package completed", 10, False, True),
]


def ensure_ipsafe_activities(db: Session) -> None:
    if db.query(IpsafeActivity).count() > 0:
        return
    for code, name, desc, seq, for_cd, for_sol in IPSAFE_ACTIVITIES:
        db.add(
            IpsafeActivity(
                code=code,
                name=name,
                description=desc,
                sequence=seq,
                required_for_cd=for_cd,
                required_for_solution=for_sol,
                is_active=True,
            )
        )
    db.commit()


def seed_database(db: Session) -> None:
    ensure_ipsafe_activities(db)
    if db.query(Initiative).count() > 0:
        return

    for name, code, seq in STAGES:
        db.add(WorkflowStage(name=name, code=code, sequence=seq))

    streams = []
    for name, code, desc in VALUE_STREAMS:
        vs = RiskValueStream(name=name, code=code, description=desc, is_active=True)
        db.add(vs)
        streams.append(vs)
    db.flush()

    teams = []
    for name, capacity in SOLUTION_TEAMS:
        team = SolutionTeam(name=name, capacity=capacity, is_active=True)
        db.add(team)
        teams.append(team)
    db.flush()

    users_data = [
        ("Vijay", "vijay@risk.local", "Administrator", None, None),
        ("Raghu", "raghu@risk.local", "Administrator", None, None),
        ("Ganesh", "ganesh@risk.local", "Administrator", None, None),
        ("Amin", "amin@risk.local", "Administrator", None, None),
        ("Priya Shah", "priya@risk.local", "Value Stream Lead", streams[0].id, None),
        ("James Okonkwo", "james@risk.local", "Value Stream Lead", streams[1].id, None),
        ("Elena Rossi", "elena@risk.local", "Value Stream Lead", streams[4].id, None),
        ("Marcus Chen", "marcus@risk.local", "Value Stream Lead", streams[6].id, None),
        ("Sofia Alvarez", "sofia@risk.local", "Value Stream Lead", streams[10].id, None),
        ("Daniel Kim", "daniel@risk.local", "Solution Lead", None, teams[0].id),
        ("Aisha Rahman", "aisha@risk.local", "Solution Lead", None, teams[1].id),
        ("Tom Bradley", "tom@risk.local", "Solution Lead", None, teams[2].id),
        ("Nina Patel", "nina@risk.local", "Solution Lead", None, teams[3].id),
    ]
    users = []
    for name, email, role, vs_id, st_id in users_data:
        user = User(
            name=name,
            email=email,
            role=role,
            value_stream_id=vs_id,
            solution_team_id=st_id,
        )
        db.add(user)
        users.append(user)
    db.flush()

    streams[0].lead_user_id = users[4].id
    streams[1].lead_user_id = users[5].id
    streams[4].lead_user_id = users[6].id
    streams[6].lead_user_id = users[7].id
    streams[10].lead_user_id = users[8].id
    teams[0].lead_user_id = users[9].id
    teams[1].lead_user_id = users[10].id
    teams[2].lead_user_id = users[11].id
    teams[3].lead_user_id = users[12].id

    today = date.today()
    initiatives = [
        dict(
            idea_id="IDEA-2026-001",
            title="AI Credit Risk Early Warning Prototype",
            value_stream_id=streams[0].id,
            owner_id=users[4].id,
            solution_team_id=teams[1].id,
            initiative_type="MVP",
            stage_code="design",
            status="Active",
            priority="High",
            readiness_pct=82,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=34,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=34),
            business_problem="Late detection of credit deterioration in mid-market portfolios.",
            proposed_concept="ML early-warning signals integrated into credit monitoring.",
            business_value="Reduce unexpected NPL formation by 8-12%.",
        ),
        dict(
            idea_id="IDEA-2026-002",
            title="Climate Risk Scenario Engine",
            value_stream_id=streams[4].id,
            owner_id=users[6].id,
            solution_team_id=None,
            initiative_type="MVP",
            stage_code="management_review",
            status="Active",
            priority="High",
            readiness_pct=55,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Pending",
            solution_approval="Not Started",
            age_days=18,
            attention_level="Red",
            attention_reason="Awaiting Vijay approval for 12 days",
            submitted_at=today - timedelta(days=18),
            business_problem="Manual climate scenario runs delay regulatory responses.",
            proposed_concept="Automated scenario engine for transition and physical risk.",
            business_value="Cut scenario turnaround from weeks to hours.",
        ),
        dict(
            idea_id="IDEA-2026-003",
            title="AML Alert Optimization",
            value_stream_id=streams[6].id,
            owner_id=users[7].id,
            solution_team_id=teams[2].id,
            initiative_type="MVP",
            stage_code="solution_review",
            status="Active",
            priority="High",
            readiness_pct=68,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Pending",
            age_days=22,
            attention_level="Amber",
            attention_reason="Solution Review pending for 9 days",
            submitted_at=today - timedelta(days=22),
            business_problem="High false-positive rate in transaction monitoring alerts.",
            proposed_concept="Risk-tiered alert scoring with analyst feedback loop.",
            business_value="Reduce false positives by 25% without increasing miss risk.",
        ),
        dict(
            idea_id="IDEA-2026-004",
            title="Counterparty Exposure AI",
            value_stream_id=streams[2].id,
            owner_id=users[4].id,
            solution_team_id=teams[0].id,
            initiative_type="Rapid Prototype",
            stage_code="requirements",
            status="Blocked",
            priority="Medium",
            readiness_pct=42,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Not Started",
            age_days=27,
            attention_level="Red",
            attention_reason="Missing data specification",
            submitted_at=today - timedelta(days=27),
            business_problem="Inconsistent exposure aggregation across trading desks.",
            proposed_concept="Unified exposure inference using trade and collateral feeds.",
            business_value="Improve same-day exposure transparency.",
        ),
        dict(
            idea_id="IDEA-2026-005",
            title="Cyber Risk Assistant",
            value_stream_id=streams[10].id,
            owner_id=users[8].id,
            solution_team_id=teams[3].id,
            initiative_type="Rapid Prototype",
            stage_code="design",
            status="Active",
            priority="Medium",
            readiness_pct=71,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=31,
            attention_level="Amber",
            attention_reason="Design stage inactive for 14 days",
            submitted_at=today - timedelta(days=31),
            business_problem="Analysts spend too long triaging cyber risk signals.",
            proposed_concept="Copilot that summarizes incident context and recommended actions.",
            business_value="Accelerate triage cycles for high-severity alerts.",
        ),
        dict(
            idea_id="IDEA-2026-006",
            title="Market Risk Stress Lab",
            value_stream_id=streams[1].id,
            owner_id=users[5].id,
            solution_team_id=teams[0].id,
            initiative_type="MVP",
            stage_code="build_in_progress",
            status="Active",
            priority="High",
            readiness_pct=88,
            ipsafe_pct=10,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=45,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=45),
            business_problem="Stress testing workflows are fragmented across tools.",
            proposed_concept="Interactive stress lab with reusable shock libraries.",
            business_value="Standardize desk-level and firm-wide stress runs.",
        ),
        dict(
            idea_id="IDEA-2026-007",
            title="Liquidity Buffer Optimizer",
            value_stream_id=streams[3].id,
            owner_id=users[5].id,
            solution_team_id=teams[1].id,
            initiative_type="Rapid Prototype",
            stage_code="ready_to_build",
            status="Active",
            priority="Medium",
            readiness_pct=90,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=29,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=29),
            business_problem="Buffer decisions rely on static rules with limited scenario coverage.",
            proposed_concept="Optimization prototype for HQLA allocation under shocks.",
            business_value="Improve buffer efficiency while meeting policy constraints.",
        ),
        dict(
            idea_id="IDEA-2026-008",
            title="Compliance Obligation Tracker",
            value_stream_id=streams[5].id,
            owner_id=users[6].id,
            solution_team_id=teams[2].id,
            initiative_type="MVP",
            stage_code="show_and_tell",
            status="Active",
            priority="Medium",
            readiness_pct=85,
            ipsafe_pct=20,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=52,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=52),
            business_problem="Obligation ownership and evidence collection is scattered.",
            proposed_concept="Central obligation map with evidence linking.",
            business_value="Reduce audit prep effort and missed control attestations.",
        ),
        dict(
            idea_id="IDEA-2026-009",
            title="Insurance Claims Anomaly Detector",
            value_stream_id=streams[7].id,
            owner_id=users[4].id,
            solution_team_id=teams[3].id,
            initiative_type="Rapid Prototype",
            stage_code="prototype_ready",
            status="Active",
            priority="Low",
            readiness_pct=92,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=60,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=60),
            business_problem="Manual sampling misses subtle claims anomalies.",
            proposed_concept="Unsupervised anomaly scoring for claims portfolios.",
            business_value="Improve detection of atypical claim patterns.",
        ),
        dict(
            idea_id="IDEA-2026-010",
            title="Audit Sampling Copilot",
            value_stream_id=streams[8].id,
            owner_id=users[7].id,
            solution_team_id=teams[0].id,
            initiative_type="MVP",
            stage_code="ipsafe_cd",
            status="Active",
            priority="Medium",
            readiness_pct=94,
            ipsafe_pct=48,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=70,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=70),
            business_problem="Audit sample design is time-consuming and inconsistent.",
            proposed_concept="Risk-weighted sampling assistant for audit engagements.",
            business_value="Increase coverage quality with less analyst time.",
        ),
        dict(
            idea_id="IDEA-2026-011",
            title="AI Model Inventory Guardian",
            value_stream_id=streams[9].id,
            owner_id=users[8].id,
            solution_team_id=teams[1].id,
            initiative_type="MVP",
            stage_code="cd_approved",
            status="Active",
            priority="High",
            readiness_pct=96,
            ipsafe_pct=55,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=78,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=78),
            business_problem="Incomplete model inventory creates governance gaps.",
            proposed_concept="Automated discovery and classification of AI/ML models.",
            business_value="Strengthen model risk oversight and inventory completeness.",
        ),
        dict(
            idea_id="IDEA-2026-012",
            title="Fraud Network Graph Explorer",
            value_stream_id=streams[6].id,
            owner_id=users[7].id,
            solution_team_id=teams[2].id,
            initiative_type="MVP",
            stage_code="deployable_solution",
            status="Active",
            priority="High",
            readiness_pct=98,
            ipsafe_pct=100,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=95,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=95),
            business_problem="Investigators struggle to visualize multi-party fraud rings.",
            proposed_concept="Interactive graph explorer with entity resolution.",
            business_value="Shorten investigation cycles for complex fraud cases.",
        ),
        dict(
            idea_id="IDEA-2026-013",
            title="Credit Limit Recommender",
            value_stream_id=streams[0].id,
            owner_id=users[4].id,
            solution_team_id=None,
            initiative_type="Rapid Prototype",
            stage_code="idea_submitted",
            status="Active",
            priority="Medium",
            readiness_pct=30,
            ipsafe_pct=0,
            raghu_approval="Pending",
            vijay_approval="Pending",
            solution_approval="Not Started",
            age_days=3,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=3),
            business_problem="Limit reviews are inconsistent across relationship managers.",
            proposed_concept="Explainable recommender for limit adjustments.",
            business_value="Improve consistency of credit limit decisions.",
        ),
        dict(
            idea_id="IDEA-2026-014",
            title="VaR Explanation Studio",
            value_stream_id=streams[1].id,
            owner_id=users[5].id,
            solution_team_id=teams[0].id,
            initiative_type="Rapid Prototype",
            stage_code="management_review",
            status="Active",
            priority="Low",
            readiness_pct=48,
            ipsafe_pct=0,
            raghu_approval="Pending",
            vijay_approval="Pending",
            solution_approval="Not Started",
            age_days=9,
            attention_level="Amber",
            attention_reason="Awaiting management review for 9 days",
            submitted_at=today - timedelta(days=9),
            business_problem="Stakeholders find VaR movements hard to interpret.",
            proposed_concept="Natural-language and visual VaR attribution studio.",
            business_value="Faster risk committee understanding of P&L drivers.",
        ),
        dict(
            idea_id="IDEA-2026-015",
            title="CCR Collateral What-If",
            value_stream_id=streams[2].id,
            owner_id=users[4].id,
            solution_team_id=teams[3].id,
            initiative_type="MVP",
            stage_code="build_in_progress",
            status="Active",
            priority="Medium",
            readiness_pct=80,
            ipsafe_pct=5,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=41,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=41),
            business_problem="Collateral what-if analysis is spreadsheet-heavy.",
            proposed_concept="Interactive what-if engine for collateral strategies.",
            business_value="Support faster collateral optimization decisions.",
        ),
        dict(
            idea_id="IDEA-2026-016",
            title="Regulatory Change Digest",
            value_stream_id=streams[5].id,
            owner_id=users[6].id,
            solution_team_id=teams[1].id,
            initiative_type="Rapid Prototype",
            stage_code="feedback",
            status="Active",
            priority="Medium",
            readiness_pct=86,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=38,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=38),
            business_problem="Teams miss relevant regulatory changes amid volume noise.",
            proposed_concept="AI digest that maps regs to owned obligations.",
            business_value="Reduce missed regulatory impact assessments.",
        ),
        dict(
            idea_id="IDEA-2026-017",
            title="Climate Disclosure Narrator",
            value_stream_id=streams[4].id,
            owner_id=users[6].id,
            solution_team_id=teams[2].id,
            initiative_type="MVP",
            stage_code="solution_candidate",
            status="Active",
            priority="High",
            readiness_pct=95,
            ipsafe_pct=72,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=88,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=88),
            business_problem="Disclosure drafting is manual and evidence-light.",
            proposed_concept="Narrative generator grounded in approved climate metrics.",
            business_value="Accelerate disclosure preparation with auditability.",
        ),
        dict(
            idea_id="IDEA-2026-018",
            title="Trade Surveillance Prioritizer",
            value_stream_id=streams[6].id,
            owner_id=users[7].id,
            solution_team_id=teams[0].id,
            initiative_type="MVP",
            stage_code="ready_to_build",
            status="Active",
            priority="High",
            readiness_pct=84,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=33,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=33),
            business_problem="Surveillance queues overwhelm analysts during volatile markets.",
            proposed_concept="Dynamic prioritization based on risk and freshness.",
            business_value="Improve time-to-first-review for high-risk alerts.",
        ),
        dict(
            idea_id="IDEA-2026-019",
            title="Cyber Control Evidence Bot",
            value_stream_id=streams[10].id,
            owner_id=users[8].id,
            solution_team_id=None,
            initiative_type="Rapid Prototype",
            stage_code="management_review",
            status="Active",
            priority="Medium",
            readiness_pct=40,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Pending",
            solution_approval="Not Started",
            age_days=11,
            attention_level="Amber",
            attention_reason="Awaiting Vijay approval for 7 days",
            submitted_at=today - timedelta(days=11),
            business_problem="Control evidence gathering is repetitive and delayed.",
            proposed_concept="Bot that collects and packages control evidence.",
            business_value="Reduce evidence collection cycle time.",
        ),
        dict(
            idea_id="IDEA-2026-020",
            title="Liquidity Intraday Monitor",
            value_stream_id=streams[3].id,
            owner_id=users[5].id,
            solution_team_id=teams[1].id,
            initiative_type="MVP",
            stage_code="design",
            status="Active",
            priority="High",
            readiness_pct=74,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=26,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=26),
            business_problem="Intraday liquidity views arrive too late for treasury action.",
            proposed_concept="Near-real-time liquidity monitor with threshold alerts.",
            business_value="Enable earlier treasury interventions.",
        ),
        dict(
            idea_id="IDEA-2026-021",
            title="Model Drift Sentinel",
            value_stream_id=streams[9].id,
            owner_id=users[8].id,
            solution_team_id=teams[3].id,
            initiative_type="MVP",
            stage_code="build_in_progress",
            status="Active",
            priority="High",
            readiness_pct=81,
            ipsafe_pct=15,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=47,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=47),
            business_problem="Model drift detection is delayed and inconsistent.",
            proposed_concept="Continuous drift monitoring with governance workflows.",
            business_value="Earlier remediation of drifting risk models.",
        ),
        dict(
            idea_id="IDEA-2026-022",
            title="Audit Issue Trend Radar",
            value_stream_id=streams[8].id,
            owner_id=users[7].id,
            solution_team_id=teams[2].id,
            initiative_type="Rapid Prototype",
            stage_code="completed",
            status="Completed",
            priority="Low",
            readiness_pct=100,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=110,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=110),
            business_problem="Issue themes across audits are hard to spot early.",
            proposed_concept="Trend radar across open and closed audit issues.",
            business_value="Surface systemic control themes for management.",
        ),
        dict(
            idea_id="IDEA-2026-023",
            title="Credit Concentration Heatmap",
            value_stream_id=streams[0].id,
            owner_id=users[4].id,
            solution_team_id=teams[0].id,
            initiative_type="Rapid Prototype",
            stage_code="prototype_ready",
            status="Active",
            priority="Medium",
            readiness_pct=91,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=54,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=54),
            business_problem="Concentration risk views are static and delayed.",
            proposed_concept="Interactive concentration heatmap by sector and geography.",
            business_value="Improve portfolio steering conversations.",
        ),
        dict(
            idea_id="IDEA-2026-024",
            title="Insurance Reserving Explainer",
            value_stream_id=streams[7].id,
            owner_id=users[4].id,
            solution_team_id=teams[1].id,
            initiative_type="MVP",
            stage_code="solution_review",
            status="Active",
            priority="Medium",
            readiness_pct=62,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Request Info",
            age_days=20,
            attention_level="Amber",
            attention_reason="Additional methodology detail requested",
            submitted_at=today - timedelta(days=20),
            business_problem="Reserving movements lack accessible explanations.",
            proposed_concept="Explainable reserving variance narrative generator.",
            business_value="Improve actuarial and management alignment.",
        ),
        dict(
            idea_id="IDEA-2026-025",
            title="Market Data Quality Sentinel",
            value_stream_id=streams[1].id,
            owner_id=users[5].id,
            solution_team_id=teams[3].id,
            initiative_type="Rapid Prototype",
            stage_code="requirements",
            status="Active",
            priority="Medium",
            readiness_pct=58,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Not Started",
            age_days=16,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=16),
            business_problem="Market data defects propagate into risk calculations.",
            proposed_concept="Automated quality checks with exception workflows.",
            business_value="Reduce calculation breaks caused by bad market data.",
        ),
        dict(
            idea_id="IDEA-2026-026",
            title="Financial Crime Case Summarizer",
            value_stream_id=streams[6].id,
            owner_id=users[7].id,
            solution_team_id=teams[2].id,
            initiative_type="MVP",
            stage_code="ipsafe_cd",
            status="Active",
            priority="High",
            readiness_pct=93,
            ipsafe_pct=50,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=66,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=66),
            business_problem="Case write-ups consume investigator capacity.",
            proposed_concept="AI case summarizer with source citations.",
            business_value="Free investigator time for higher-value analysis.",
        ),
        dict(
            idea_id="IDEA-2026-027",
            title="AI Prompt Risk Scanner",
            value_stream_id=streams[9].id,
            owner_id=users[8].id,
            solution_team_id=None,
            initiative_type="Rapid Prototype",
            stage_code="idea_submitted",
            status="Active",
            priority="High",
            readiness_pct=25,
            ipsafe_pct=0,
            raghu_approval="Pending",
            vijay_approval="Pending",
            solution_approval="Not Started",
            age_days=2,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=2),
            business_problem="GenAI usage introduces unmanaged prompt and data leakage risk.",
            proposed_concept="Scanner for risky prompts and sensitive content patterns.",
            business_value="Improve AI usage control posture.",
        ),
        dict(
            idea_id="IDEA-2026-028",
            title="Climate Physical Risk Mapper",
            value_stream_id=streams[4].id,
            owner_id=users[6].id,
            solution_team_id=teams[0].id,
            initiative_type="MVP",
            stage_code="show_and_tell",
            status="Active",
            priority="High",
            readiness_pct=87,
            ipsafe_pct=25,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=49,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=49),
            business_problem="Physical risk exposure mapping is fragmented by asset class.",
            proposed_concept="Unified geospatial physical risk mapper.",
            business_value="Improve board-ready physical risk visibility.",
        ),
        dict(
            idea_id="IDEA-2026-029",
            title="Compliance Policy Diff Assistant",
            value_stream_id=streams[5].id,
            owner_id=users[6].id,
            solution_team_id=teams[1].id,
            initiative_type="Rapid Prototype",
            stage_code="completed",
            status="Completed",
            priority="Low",
            readiness_pct=100,
            ipsafe_pct=0,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=102,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=102),
            business_problem="Policy revisions are hard to compare and communicate.",
            proposed_concept="Semantic diff assistant for policy versions.",
            business_value="Accelerate policy review and stakeholder communication.",
        ),
        dict(
            idea_id="IDEA-2026-030",
            title="Cyber Threat Narrative Board",
            value_stream_id=streams[10].id,
            owner_id=users[8].id,
            solution_team_id=teams[3].id,
            initiative_type="MVP",
            stage_code="deployable_solution",
            status="Active",
            priority="Medium",
            readiness_pct=97,
            ipsafe_pct=100,
            raghu_approval="Approved",
            vijay_approval="Approved",
            solution_approval="Accepted",
            age_days=91,
            attention_level="Green",
            attention_reason=None,
            submitted_at=today - timedelta(days=91),
            business_problem="Threat briefings lack consistent narrative structure.",
            proposed_concept="Board-ready cyber threat narrative generator.",
            business_value="Improve executive cyber risk communication quality.",
        ),
    ]

    for item in initiatives:
        init = Initiative(**item)
        db.add(init)
    db.flush()

    first = db.query(Initiative).filter_by(idea_id="IDEA-2026-001").one()
    db.add(
        Document(
            initiative_id=first.id,
            filename="Credit_Early_Warning_Concept.pptx",
            document_type="PowerPoint",
            uploaded_by="Priya Shah",
            uploaded_at=today - timedelta(days=33),
            version="1.2",
        )
    )
    db.add(
        Document(
            initiative_id=first.id,
            filename="Business_Requirements.docx",
            document_type="Word",
            uploaded_by="Priya Shah",
            uploaded_at=today - timedelta(days=30),
            version="1.0",
        )
    )
    db.add(
        ActivityLog(
            initiative_id=first.id,
            actor="Priya Shah",
            action="Submitted idea",
            detail="Initial submission with concept deck",
        )
    )
    db.add(
        ActivityLog(
            initiative_id=first.id,
            actor="Raghu",
            action="Approved management review",
            detail="Approved for solution readiness",
        )
    )

    notifications = [
        ("Vijay", "4 initiatives require your approval."),
        ("Raghu", "Climate Risk Scenario Engine has been waiting for review for 8 days."),
        ("Solution Team 3", "2 approved initiatives require acceptance."),
        ("Priya Shah", "Additional data requirements requested on Counterparty Exposure AI."),
    ]
    for recipient, message in notifications:
        db.add(Notification(recipient=recipient, message=message))

    db.commit()
